### ISSUE TITLE
Italics on variables?

### ISSUE THREAD

**Issue by BrunoUY** [leifcr/pine-script-syntax-highlighting#1]
Hi, 

First of all, thank you for doing this extension!!!

I have one question, do you know why the variable definition appear in italics? It's something in my configuration of VScode?

![image](https://user-images.githubusercontent.com/4197644/48653369-7683d780-e9e3-11e8-8fb6-7a4340353760.png)

**Comment by leifcr** [comment]
It's from the theme you have setup, as this only tells the style what kind of style it should use, while the style applies the formatting.
