### ISSUE TITLE
Syntax highlight broken with last release

### ISSUE THREAD

**Issue by Jos512** [leifcr/pine-script-syntax-highlighting#6]
The newest version of the syntax highlight is broken; Pine code isn't highlighted anymore.

Example with the latest Visual Studio Code version (1.50.1):

![2020-11-04_08-38-25](https://user-images.githubusercontent.com/13403160/98082543-355b8b00-1e79-11eb-929f-40b83893c031.png)

In your testing the syntax probably worked fine, so I'm not sure why it doesn't work in the live environment now. I'll take a look at it.

_Edit:_ I see that some of the regexes with this pattern at their end `(?=\\()` don't validate precisely because there is apparently a final `)` missing. I however didn't add those to the Pine syntax highlight, since [the original file](https://github.com/leifcr/pine-script-syntax-highlighting/commit/d7c75730baf7f225735ae0dc0efb516f3b73292f#diff-441d0d785af09bd7624cf59ce8f8726482c3526d14b8f19c1ed3c33f09b49c78R75) neither uses a final `)` parenthesis (and the original file worked good). Please share your thoughts since you know this best.

**Comment by leifcr** [comment]
Let me recheck that. Should work, as it works locally.

**Comment by leifcr** [comment]
Fixed in commit 036b4352d3a5ebe5ec37418286fffe1ac94c9a8e, and released as version 0.1.5

**Comment by Jos512** [comment]
Awesome, thanks a lot! Also thanks for the quick turnaround. :slightly_smiling_face: 

For my own learning so I don't make the same mistake with future contributions, what went wrong? From the commit I see a lot of whitespace changes, was that the problem?

**Comment by leifcr** [comment]
It was an additional | on a line. Typos happen, and i should have tested more.

**Comment by leifcr** [comment]
The whitespaces was just 'remove whitespaces on save extension'
