### ISSUE TITLE
Logical operators not highlighted

### ISSUE THREAD

**Issue by naanee** [leifcr/pine-script-syntax-highlighting#8]
Hi,

I noticed that all the logical operators don't highlight.

Is it possible to color them all (i.e.: red)?

![Screenshot 2021-05-14 205404](https://user-images.githubusercontent.com/79833870/118316319-f7f64b00-b4f6-11eb-83c3-a9b87b81d78f.png)

Regards,
Naanee

**Comment by leifcr** [comment]
closing this, as I'm archiving the project.
